### ISSUE TITLE
.net code metrics failed after latest changes

### ISSUE THREAD

**Issue by pashkapashka** [dotnet/samples#5640] opened 2023-01-24 10:41 UTC
**Before you open an issue**

If the issue is:

pipeline: https://github.com/dotnet/samples/actions/runs/3480443578
commit: https://github.com/dotnet/samples/commit/b74154f90fba167d2323d81fe07fefb0e554f799

`    - name: Set output
      run: |
        echo "updated-metrics=updatedMetrics" >> $GITHUB_OUTPUT
        echo "summary-title=title" >> $GITHUB_OUTPUT
        echo "summary-details=summary" >> $GITHUB_OUTPUT`

can't set output, have error:

Unable to process file command 'output' successfully.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by erichiller** [comment] 2023-06-13 16:00
Same here, the issue is multiline output. Some more information [here](https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully).

This is the problem line:
https://github.com/dotnet/samples/blob/66506ef1d98d3579a35708717325ac6e5e676f28/github-actions/DotNet.GitHubAction/DotNet.GitHubAction/Program.cs#L57

**Comment by IEvangelist** [comment] 2023-10-30 20:34
Closed by #6272

**Closed by IEvangelist** 2023-10-30 20:34 UTC
Labels: :world_map: reQUEST
