### ISSUE TITLE
Unused code samples

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/samples#1434] opened 2019-09-07 07:44 UTC
There might be alot of unused code samples that needs to be removed.
Is there an easy way to determine if a specific sample is used or not ?
The samples here are used by `dotnet/docs` and `dotnet/dotnet-api-docs`, are there any other repos ?

**Comment by Youssef1313** [comment] 2019-09-07 09:16
I've written a small C# program to determine the unused snippets but want to make sure if it's correct ?
For now, it only checks in `dotnet/docs` but not `dotnet/dotnet-api-docs` and only for `.vb` files.

```csharp
void Main()
{
    // Get .vb files in my local fork of samples.
    // Replacing \ with (\\|\/) is used later for regex, so it matches both \ and /
    var vbSamples = Directory.GetFiles(@"D:\dotnet\samples\samples\", "*.vb", SearchOption.AllDirectories)
                            .Select(s => s.Replace(@"D:\dotnet\samples\samples\", "").Replace(@"\", @"(\\|\/)").ToLower()).ToArray();

    // Get .md files in my local fork of docs
    var docsMarkdown = Directory.GetFiles(@"D:\dotnet\docs\docs\", "*.md", SearchOption.AllDirectories);


    for (var i = 0; i < vbSamples.Length; i++)
    {
        var isUsedSample = false;
        foreach (var mdFile in docsMarkdown)
        {
            if (System.Text.RegularExpressions.Regex.IsMatch(File.ReadAllText(mdFile).ToLower(), vbSamples[i]))
            {
                isUsedSample = true;
                break;
            }
        }
        if (!isUsedSample) Console.WriteLine(vbSamples[i]);
    }
}
```

**Comment by mairaw** [comment] 2019-10-01 03:04
I'll close this one as duplicate of dotnet/docs#14825. I think @rpetrusha was also working on a code to identify those.

**Closed by mairaw** 2019-10-01 03:04 UTC
